### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by Zeyad-Zaky** [bramus/react-native-maps-directions#71]
I have a good working map view, when I add map view directions the app crashes, I tried using your example to check if I have a problem with my code but still get the same result, after the map renders the app crashes and closes

**Comment by bramus** [comment]
I'm gonna need some more info:
- Platform: `ios` or `android`
- Versions of `react-native`,  `react`,  `react-native-maps`,  `react-native-maps-directions`

**Comment by bsef15m007** [comment]
Ap crashes when i render <MapViewDirections> inside <MapView> platform:Android
"react": "^16.6.3",
 "react-native": "0.58.6",
"react-native-maps": "^0.23.0",
"react-native-maps-directions": "^1.6.0",

**Comment by INBINCOMOBI** [comment]
I am having same exact issue. Works fine in IOS. App crashes in Android
react - 16.8.8
react-native - 0.59.9
react-native-maps - 0.24.2
react-native-maps-directions - 1.7.0

**Comment by bramus** [comment]
What does `adb logcat` tell you? You should be able to derive what causes the crash from its output.

**Comment by INBINCOMOBI** [comment]
thanks. Not sure I understand. Do you mean by using something like /react-native-android-log?

**Comment by bramus** [comment]
https://developer.android.com/studio/command-line/adb

**Comment by INBINCOMOBI** [comment]
and here is what I am getting. any ideas? these are my dependencies:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/model/RoundCap;ava.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/model/RoundCap; (see below dependencies for more error info)
=====================================================
dependencies {
    implementation project(':react-native-localize')
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.facebook.react:react-native:+' // From node_modules
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':react-native-navigation')
    implementation project(':react-native-vector-icons')
    implementation (project(':react-native-maps')) {
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-base:10.0.1'
    implementation 'com.google.android.gms:play-services-maps:10.0.1'
    implementation project(':react-native-sqlite-storage')
    implementation project(':react-native-localize')
 }
============================================================

    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/model/RoundCap;
        at com.airbnb.android.react.maps.AirMapPolyline.<init>(AirMapPolyline.java:32)
        at com.airbnb.android.react.maps.AirMapPolylineManager.createViewInstance(AirMapPolylineManager.java:46)
        at com.airbnb.android.react.maps.AirMapPolylineManager.createViewInstance(AirMapPolylineManager.java:24)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:256)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:983)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:24)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by bramus** [comment]
There was a comment here with some output from `adb logcat`. It read:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/model/RoundCap;
    at com.airbnb.android.react.maps.AirMapPolyline.<init>(AirMapPolyline.java:32)
    at com.airbnb.android.react.maps.AirMapPolylineManager.createViewInstance(AirMapPolylineManager.java:46)
    at com.airbnb.android.react.maps.AirMapPolylineManager.createViewInstance(AirMapPolylineManager.java:24)
    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:256)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
    at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:983)
    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:24)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Please refer to https://github.com/react-native-community/react-native-maps/issues/2693 in order to fix it.
